/* LoanRepo — Supabase credentials. */
window.LOANREPO_SUPABASE={url:"https://ipshimfcquhjkbbypghj.supabase.co",anonKey:"sb_publishable_Ytd_Lbk5_5PZ6IjWZxZOBg_qdhBtUJG"};
document.write('<script src="./loanrepo-db-compat.js?v=20260916-2"><\/script>');
(function(){var h="./loanrepo-readable.css?v=20260916";if(!document.querySelector('link[data-loanrepo-readable]')){var l=document.createElement("link");l.rel="stylesheet";l.href=h;l.setAttribute("data-loanrepo-readable","true");document.head.appendChild(l)}})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-ebook-account]'))return;var s=document.createElement("script");s.src="./loanrepo-ebook-account-v3.js?v=20260916-5";s.async=false;s.setAttribute("data-loanrepo-ebook-account","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-stage1-privacy]'))return;var s=document.createElement("script");s.src="./loanrepo-stage1-privacy-bridge.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-stage1-privacy","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-track-bridge]'))return;var s=document.createElement("script");s.src="./loanrepo-track-bridge.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-track-bridge","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-track-auth-copy]'))return;var s=document.createElement("script");s.src="./loanrepo-track-auth-copy.js?v=20260916-2";s.async=false;s.setAttribute("data-loanrepo-track-auth-copy","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-stage1-flow]'))return;var s=document.createElement("script");s.src="./loanrepo-stage1-flow.js?v=20260916-5";s.async=false;s.setAttribute("data-loanrepo-stage1-flow","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-ebook-name]'))return;var s=document.createElement("script");s.src="./loanrepo-ebook-name.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-ebook-name","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-documents]'))return;var s=document.createElement("script");s.src="./loanrepo-documents.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-documents","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-conversion-order]'))return;var s=document.createElement("script");s.src="./loanrepo-conversion-order.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-conversion-order","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-stage1-pdf-cleanup]'))return;var s=document.createElement("script");s.src="./loanrepo-stage1-pdf-cleanup.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-stage1-pdf-cleanup","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
(function(){function load(){if(document.querySelector('script[data-loanrepo-reconciliation]'))return;var s=document.createElement("script");s.src="./loanrepo-reconciliation.js?v=20260916-1";s.async=false;s.setAttribute("data-loanrepo-reconciliation","true");document.head.appendChild(s)}if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",load,{once:true});else load()})();
